### ISSUE TITLE
no "Edgebee" window

### ISSUE THREAD

**Issue by raven128** [kenaniah/swords-and-potions-2-bot#3]
C:_apps\swords-and-potions-2-bot-master>snp2-bot.py
Traceback (most recent call last):
  File "C:_apps\swords-and-potions-2-bot-master\snp2-bot.py", line 23, in <module>    switch_to('Edgebee')
  File "C:\automa\library.zip\automa\api.py", line 324, in switch_to
  File "<string>", line 2, in switch_to
  File "bfs_console\util\hints.pyc", line 10, in give_hint_on_unicode_decode_error
  File "automa\api_impl__init__.pyc", line 256, in switch_to
  File "C:\automa\library.zip\automa\api.py", line 1194, in handle
  File "C:\automa\library.zip\automa\api.py", line 436, in _first_occurrence
  File "C:\automa\library.zip\automa\api.py", line 1207, in _raise_not_found_error
LookupError: There is no window with title matching 'Edgebee'. 
To see which windows are available, use:
        find_all(Window())

**Comment by raven128** [comment]
i suppose that error occure because one must start the game from edgebee site, so the would be a window with Edgebee in it's caption. so i've started IE, and began new game session.
now i see that error:
C:_apps\swords-and-potions-2-bot-master>snp2-bot.py
Traceback (most recent call last):
  File "C:_apps\swords-and-potions-2-bot-master\snp2-bot.py", line 65, in <module>
    build_cycle_indexes = {x: -1 for x in os.listdir(cycle_path) if os.path.isdir(os.path.join(cycle_path, x))}
WindowsError: [Error 3] : 'build-cycles/_._'

**Comment by kenaniah** [comment]
Just added a long-overdue readme. Also added an example build-cycles directory which should fix your issue. Please feel free to open another one if you run into something else :-)
